/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package principal;

import Dao.CarnicosDAO;
import Modelo.Carnicos;
import javax.swing.JOptionPane;

/**
 *
 * @author Bryan
 */
public class usuario_administrador extends javax.swing.JFrame {

    /**
     * Creates new form usuario_administrador
     */
    public usuario_administrador() {
        initComponents();
        this.setLocationRelativeTo(null);
        this.setTitle("Registro de Productos Carnicos");
    }

    private void LimpiarCampos(){
        txtNombre_Carnico.setText("");
        txtPrecio_Carnico_Kg.setText("");
        txtPrecio_Carnico_Lb.setText("");
        txtCantidad.setText("");
        txtProcedencia.setText("");
        cbxTipo_Carnico.setSelectedItem("Seleccionar");
        txtId_Carnico.setText("");
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        cbxTipo_Carnico = new javax.swing.JComboBox<>();
        jLabel7 = new javax.swing.JLabel();
        txtNombre_Carnico = new javax.swing.JTextField();
        txtPrecio_Carnico_Kg = new javax.swing.JTextField();
        txtPrecio_Carnico_Lb = new javax.swing.JTextField();
        txtCantidad = new javax.swing.JTextField();
        txtProcedencia = new javax.swing.JTextField();
        btnRegistrar = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        btnActualizar = new javax.swing.JButton();
        btnEliminar = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        txtId_Carnico = new javax.swing.JTextField();
        btnBuscar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Bienvenido Usuario Administrador");

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Datios de los Carnicos"));

        jLabel2.setText("Nombre Carnico:");

        jLabel3.setText("Precio Carnico por Kg:");

        jLabel4.setText("Precio Carnico por Lb:");

        jLabel5.setText("Cantidad Total:");

        jLabel6.setText("Procedencia:");

        cbxTipo_Carnico.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccionar", "Carne de Vaca", "Carne de Cerdo", "Carne de Borrego", "Carne de Venado" }));

        jLabel7.setText("Tipo de Carnico:");

        btnRegistrar.setText("Registrar");
        btnRegistrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegistrarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel4)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel3)
                                .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addGap(37, 37, 37)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(jLabel7)
                                        .addComponent(jLabel6)
                                        .addComponent(jLabel5)))))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtPrecio_Carnico_Kg, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtNombre_Carnico, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtPrecio_Carnico_Lb, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtCantidad, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtProcedencia, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cbxTipo_Carnico, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(90, 90, 90)
                        .addComponent(btnRegistrar, javax.swing.GroupLayout.PREFERRED_SIZE, 214, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(27, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtNombre_Carnico, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtPrecio_Carnico_Kg, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtPrecio_Carnico_Lb, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtCantidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtProcedencia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cbxTipo_Carnico, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7))
                .addGap(18, 18, 18)
                .addComponent(btnRegistrar)
                .addContainerGap(14, Short.MAX_VALUE))
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Opciones"));

        btnActualizar.setText("Actualizar");
        btnActualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnActualizarActionPerformed(evt);
            }
        });

        btnEliminar.setText("Eliminar");
        btnEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarActionPerformed(evt);
            }
        });

        jLabel8.setText("Buscar por Id:");

        btnBuscar.setText("Buscar");
        btnBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnEliminar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnActualizar, javax.swing.GroupLayout.DEFAULT_SIZE, 134, Short.MAX_VALUE)
                    .addComponent(txtId_Carnico)
                    .addComponent(btnBuscar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(18, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(txtId_Carnico, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(17, 17, 17)
                .addComponent(btnBuscar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnActualizar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnEliminar)
                .addContainerGap(12, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(246, 246, 246)
                        .addComponent(jLabel1)))
                .addContainerGap(30, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(82, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnRegistrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegistrarActionPerformed
        CarnicosDAO carnicosdao = new CarnicosDAO();
        Carnicos carnicos = new Carnicos();
        
       
        
        if(txtNombre_Carnico.getText().equals("") || txtPrecio_Carnico_Kg.getText().equals("") || 
                txtPrecio_Carnico_Lb.getText().equals("") || txtCantidad.getText().equals("") || 
                txtProcedencia.getText().equals("") || cbxTipo_Carnico.getSelectedItem().toString().equals("")){
            JOptionPane.showMessageDialog(null, "Ingrese los Datos Correcpondientes en los Campos de Texto");
        }else{
            
            String nombre_carnico = txtNombre_Carnico.getText();
            Double precio_carnico_kg = Double.parseDouble(txtPrecio_Carnico_Kg.getText());
            Double precio_carnico_lb = Double.parseDouble(txtPrecio_Carnico_Lb.getText());
            Double cantidad_producto = Double.parseDouble(txtCantidad.getText());
            String procedencia = txtProcedencia.getText();
            String tipo_carnico = cbxTipo_Carnico.getSelectedItem().toString();
            
            carnicos.setCarnicos(nombre_carnico);
            carnicos.setPrecio_carnicos_kilos(precio_carnico_kg);
            carnicos.setPrecio_carnicos_libras(precio_carnico_lb);
            carnicos.setCantidad(cantidad_producto);
            carnicos.setProcedencia(procedencia);
            carnicos.setTipo_carnico(tipo_carnico);
            carnicosdao.registrar(carnicos);
            
            JOptionPane.showMessageDialog(null, "Registro del Carnico Exitoso");
            LimpiarCampos();
        }
    }//GEN-LAST:event_btnRegistrarActionPerformed

    private void btnActualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnActualizarActionPerformed
        CarnicosDAO carnicosdao = new CarnicosDAO();
        Carnicos carnicos = new Carnicos();
        
        
        if(txtNombre_Carnico.getText().equals("") || txtPrecio_Carnico_Kg.getText().equals("") || txtPrecio_Carnico_Lb.getText().equals("") || txtCantidad.getText().equals("") || txtProcedencia.getText().equals("") || cbxTipo_Carnico.getSelectedItem().toString().equals("")){
            JOptionPane.showMessageDialog(null, "Por favor Ingrese la Información en los Campos para Modificar el Registro Seleccionado");
        }else{
            
            int id_carnicos = Integer.parseInt(txtId_Carnico.getText());
            String nombre_carnico = txtNombre_Carnico.getText();
            Double precio_carnico_kg = Double.parseDouble(txtPrecio_Carnico_Kg.getText());
            Double precio_carnico_lb = Double.parseDouble(txtPrecio_Carnico_Lb.getText());
            Double cantidad_producto = Double.parseDouble(txtCantidad.getText());
            String procedencia = txtProcedencia.getText();
            String tipo_carnico = cbxTipo_Carnico.getSelectedItem().toString();
        
            carnicos.setId_carnicos(id_carnicos);
            carnicos.setCarnicos(nombre_carnico);
            carnicos.setPrecio_carnicos_kilos(precio_carnico_kg);
            carnicos.setPrecio_carnicos_libras(precio_carnico_lb);
            carnicos.setCantidad(cantidad_producto);
            carnicos.setProcedencia(procedencia);
            carnicos.setTipo_carnico(tipo_carnico);
            
            carnicosdao.actualizar(carnicos);
            LimpiarCampos();
            JOptionPane.showMessageDialog(null, "Información del Registro Actualizado con Exito");
        }
    }//GEN-LAST:event_btnActualizarActionPerformed

    private void btnBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarActionPerformed
        CarnicosDAO carnicosdao = new CarnicosDAO();
        Carnicos carnicos = new Carnicos();
        
        if(txtId_Carnico.getText().equals("")){
            JOptionPane.showMessageDialog(null, "Ingrese un Id para buscar el carnico que desee");
        }else{
            int id_carnico = Integer.parseInt(txtId_Carnico.getText());
            carnicos.setId_carnicos(id_carnico);
            carnicosdao.buscar(carnicos);
            
            txtNombre_Carnico.setText(carnicos.getCarnicos());
            txtPrecio_Carnico_Kg.setText(String.valueOf(carnicos.getPrecio_carnicos_kilos()));
            txtPrecio_Carnico_Lb.setText(String.valueOf(carnicos.getPrecio_carnicos_libras()));
            txtCantidad.setText(String.valueOf(carnicos.getCantidad()));
            txtProcedencia.setText(carnicos.getProcedencia());
            cbxTipo_Carnico.setSelectedItem(carnicos.getTipo_carnico());
            
            JOptionPane.showMessageDialog(null, "Registro Encontrado con Exito");
        }
    }//GEN-LAST:event_btnBuscarActionPerformed

    private void btnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarActionPerformed
        CarnicosDAO carnicosdao = new CarnicosDAO();
        Carnicos carnicos = new Carnicos();
        
        if(txtId_Carnico.getText().equals("")){
            JOptionPane.showMessageDialog(null, "Por Favor Ingrese un Id para Eliminar un Registro");
        }else{
            int id_carnicos = Integer.parseInt(txtId_Carnico.getText());
            carnicos.setId_carnicos(id_carnicos);
            carnicosdao.eliminar(carnicos);
            LimpiarCampos();
            JOptionPane.showMessageDialog(null, "Registro Eliminado con Exito");
        }
    }//GEN-LAST:event_btnEliminarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(usuario_administrador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(usuario_administrador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(usuario_administrador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(usuario_administrador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new usuario_administrador().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnActualizar;
    private javax.swing.JButton btnBuscar;
    private javax.swing.JButton btnEliminar;
    private javax.swing.JButton btnRegistrar;
    private javax.swing.JComboBox<String> cbxTipo_Carnico;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JTextField txtCantidad;
    private javax.swing.JTextField txtId_Carnico;
    private javax.swing.JTextField txtNombre_Carnico;
    private javax.swing.JTextField txtPrecio_Carnico_Kg;
    private javax.swing.JTextField txtPrecio_Carnico_Lb;
    private javax.swing.JTextField txtProcedencia;
    // End of variables declaration//GEN-END:variables
}
