
package clientews.servicio;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.10
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "ServicioSumaImplService", targetNamespace = "http://beans/", wsdlLocation = "http://localhost:8095/ServicioSumaImplService/ServicioSumaImpl?wsdl")
public class ServicioSumaImplService
    extends Service
{

    private final static URL SERVICIOSUMAIMPLSERVICE_WSDL_LOCATION;
    private final static WebServiceException SERVICIOSUMAIMPLSERVICE_EXCEPTION;
    private final static QName SERVICIOSUMAIMPLSERVICE_QNAME = new QName("http://beans/", "ServicioSumaImplService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:8095/ServicioSumaImplService/ServicioSumaImpl?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        SERVICIOSUMAIMPLSERVICE_WSDL_LOCATION = url;
        SERVICIOSUMAIMPLSERVICE_EXCEPTION = e;
    }

    public ServicioSumaImplService() {
        super(__getWsdlLocation(), SERVICIOSUMAIMPLSERVICE_QNAME);
    }

    public ServicioSumaImplService(WebServiceFeature... features) {
        super(__getWsdlLocation(), SERVICIOSUMAIMPLSERVICE_QNAME, features);
    }

    public ServicioSumaImplService(URL wsdlLocation) {
        super(wsdlLocation, SERVICIOSUMAIMPLSERVICE_QNAME);
    }

    public ServicioSumaImplService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, SERVICIOSUMAIMPLSERVICE_QNAME, features);
    }

    public ServicioSumaImplService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public ServicioSumaImplService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns ServicioSumarWS
     */
    @WebEndpoint(name = "ServicioSumaImplPort")
    public ServicioSumarWS getServicioSumaImplPort() {
        return super.getPort(new QName("http://beans/", "ServicioSumaImplPort"), ServicioSumarWS.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns ServicioSumarWS
     */
    @WebEndpoint(name = "ServicioSumaImplPort")
    public ServicioSumarWS getServicioSumaImplPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://beans/", "ServicioSumaImplPort"), ServicioSumarWS.class, features);
    }

    private static URL __getWsdlLocation() {
        if (SERVICIOSUMAIMPLSERVICE_EXCEPTION!= null) {
            throw SERVICIOSUMAIMPLSERVICE_EXCEPTION;
        }
        return SERVICIOSUMAIMPLSERVICE_WSDL_LOCATION;
    }

}
