
package practica;

import java.awt.Color;
import javax.swing.JLabel;
import javax.swing.JOptionPane;

/**
 *
 * @author Bryan
 */
public class diseño extends javax.swing.JFrame {

    
    public String turnoX = "X";
    public String turnoO = "O";
    
    JLabel[] arreglo = new JLabel[9];
    
    int matrizGanadora[][] = {{1,2,3},{4,5,6},{7,8,9},{1,4,7},{2,5,8},{3,6,9},{1,5,9},{3,5,7}};
    
    public boolean estado = true;
    
    
    public diseño() {
        initComponents();
        this.setLocationRelativeTo(null);
        this.setTitle("Juego de Tiqui Tracas");
        arreglo[0] = lblabel1;
        arreglo[1] = lblable2;
        arreglo[2] = lblabel3;
        arreglo[3] = lblable4;
        arreglo[4] = lblable5;
        arreglo[5] = lblable6;
        arreglo[6] = lblable7;
        arreglo[7] = lblable8;
        arreglo[8] = lblable9;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        lblabel1 = new javax.swing.JLabel();
        lblable2 = new javax.swing.JLabel();
        lblabel3 = new javax.swing.JLabel();
        lblable4 = new javax.swing.JLabel();
        lblable5 = new javax.swing.JLabel();
        lblable6 = new javax.swing.JLabel();
        lblable7 = new javax.swing.JLabel();
        lblable8 = new javax.swing.JLabel();
        lblable9 = new javax.swing.JLabel();
        btnLimpiar = new javax.swing.JButton();
        btnSalir = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jPanel2.setBackground(new java.awt.Color(0, 0, 0));

        lblabel1.setBackground(new java.awt.Color(255, 255, 255));
        lblabel1.setFont(new java.awt.Font("Segoe UI", 1, 48)); // NOI18N
        lblabel1.setForeground(new java.awt.Color(0, 0, 0));
        lblabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblabel1.setOpaque(true);
        lblabel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                lblabel1MousePressed(evt);
            }
        });

        lblable2.setBackground(new java.awt.Color(255, 255, 255));
        lblable2.setFont(new java.awt.Font("Segoe UI", 1, 48)); // NOI18N
        lblable2.setForeground(new java.awt.Color(0, 0, 0));
        lblable2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblable2.setOpaque(true);
        lblable2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                lblable2MousePressed(evt);
            }
        });

        lblabel3.setBackground(new java.awt.Color(255, 255, 255));
        lblabel3.setFont(new java.awt.Font("Segoe UI", 1, 48)); // NOI18N
        lblabel3.setForeground(new java.awt.Color(0, 0, 0));
        lblabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblabel3.setOpaque(true);
        lblabel3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                lblabel3MousePressed(evt);
            }
        });

        lblable4.setBackground(new java.awt.Color(255, 255, 255));
        lblable4.setFont(new java.awt.Font("Segoe UI", 1, 48)); // NOI18N
        lblable4.setForeground(new java.awt.Color(0, 0, 0));
        lblable4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblable4.setOpaque(true);
        lblable4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                lblable4MousePressed(evt);
            }
        });

        lblable5.setBackground(new java.awt.Color(255, 255, 255));
        lblable5.setFont(new java.awt.Font("Segoe UI", 1, 48)); // NOI18N
        lblable5.setForeground(new java.awt.Color(0, 0, 0));
        lblable5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblable5.setOpaque(true);
        lblable5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                lblable5MousePressed(evt);
            }
        });

        lblable6.setBackground(new java.awt.Color(255, 255, 255));
        lblable6.setFont(new java.awt.Font("Segoe UI", 1, 48)); // NOI18N
        lblable6.setForeground(new java.awt.Color(0, 0, 0));
        lblable6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblable6.setOpaque(true);
        lblable6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                lblable6MousePressed(evt);
            }
        });

        lblable7.setBackground(new java.awt.Color(255, 255, 255));
        lblable7.setFont(new java.awt.Font("Segoe UI", 1, 48)); // NOI18N
        lblable7.setForeground(new java.awt.Color(0, 0, 0));
        lblable7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblable7.setOpaque(true);
        lblable7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                lblable7MousePressed(evt);
            }
        });

        lblable8.setBackground(new java.awt.Color(255, 255, 255));
        lblable8.setFont(new java.awt.Font("Segoe UI", 1, 48)); // NOI18N
        lblable8.setForeground(new java.awt.Color(0, 0, 0));
        lblable8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblable8.setOpaque(true);
        lblable8.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                lblable8MousePressed(evt);
            }
        });

        lblable9.setBackground(new java.awt.Color(255, 255, 255));
        lblable9.setFont(new java.awt.Font("Segoe UI", 1, 48)); // NOI18N
        lblable9.setForeground(new java.awt.Color(0, 0, 0));
        lblable9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblable9.setOpaque(true);
        lblable9.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                lblable9MousePressed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(lblable4, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 123, Short.MAX_VALUE)
                    .addComponent(lblabel1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblable7, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lblable2, javax.swing.GroupLayout.DEFAULT_SIZE, 109, Short.MAX_VALUE)
                    .addComponent(lblable5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblable8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblable6, javax.swing.GroupLayout.DEFAULT_SIZE, 118, Short.MAX_VALUE)
                    .addComponent(lblable9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lblabel3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 124, Short.MAX_VALUE)
                    .addComponent(lblabel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblable2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblable5, javax.swing.GroupLayout.DEFAULT_SIZE, 126, Short.MAX_VALUE)
                    .addComponent(lblable6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblable4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lblable7, javax.swing.GroupLayout.DEFAULT_SIZE, 132, Short.MAX_VALUE)
                    .addComponent(lblable8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblable9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );

        btnLimpiar.setText("Limpiar");
        btnLimpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimpiarActionPerformed(evt);
            }
        });

        btnSalir.setText("Salir");
        btnSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalirActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(btnLimpiar, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(126, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(125, 125, 125))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(btnSalir, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(44, 44, 44))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(btnLimpiar, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31)
                .addComponent(btnSalir, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(33, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalirActionPerformed
        System.exit(0);
    }//GEN-LAST:event_btnSalirActionPerformed

    private void lblabel1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblabel1MousePressed
        presionarCasilla(1);
    }//GEN-LAST:event_lblabel1MousePressed

    private void lblable2MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblable2MousePressed
        presionarCasilla(2);
    }//GEN-LAST:event_lblable2MousePressed

    private void lblabel3MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblabel3MousePressed
        presionarCasilla(3);
    }//GEN-LAST:event_lblabel3MousePressed

    private void lblable4MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblable4MousePressed
        presionarCasilla(4);
    }//GEN-LAST:event_lblable4MousePressed

    private void lblable5MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblable5MousePressed
        presionarCasilla(5);
    }//GEN-LAST:event_lblable5MousePressed

    private void lblable6MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblable6MousePressed
        presionarCasilla(6);
    }//GEN-LAST:event_lblable6MousePressed

    private void lblable7MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblable7MousePressed
        presionarCasilla(7);
    }//GEN-LAST:event_lblable7MousePressed

    private void lblable8MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblable8MousePressed
        presionarCasilla(8);
    }//GEN-LAST:event_lblable8MousePressed

    private void lblable9MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblable9MousePressed
        presionarCasilla(9);
    }//GEN-LAST:event_lblable9MousePressed

    private void btnLimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimpiarActionPerformed
        limpiarJuego();
    }//GEN-LAST:event_btnLimpiarActionPerformed
    
    
    public void presionarCasilla(int casilla){
        if(arreglo[casilla-1].getText().equals("") && estado){
            arreglo[casilla-1].setText(turnoX);
            cambiarTurno();
            comprobarGanador();
        }
    }
    
    public void cambiarTurno(){
        if(turnoX.equals("X")){
            turnoX = "O";
            estado = true;
        }else{
            turnoX = "X";
            estado = true;
        }
    }
    
    public void limpiarJuego(){
        for (int i = 0; i < arreglo.length; i++) {
            arreglo[i].setText("");
            arreglo[i].setBackground(Color.white);
            estado = true;
        }
    }
    
    public void comprobarGanador(){
        for (int i = 0; i < matrizGanadora.length; i++) {
            if(arreglo[matrizGanadora[i][0]-1].getText().equals("X") && arreglo[matrizGanadora[i][1]-1].getText().equals("X") && arreglo[matrizGanadora[i][2]-1].getText().equals("X")){
                arreglo[matrizGanadora[i][0]-1].setBackground(Color.green);
                arreglo[matrizGanadora[i][1]-1].setBackground(Color.green);
                arreglo[matrizGanadora[i][2]-1].setBackground(Color.green);
                JOptionPane.showMessageDialog(null, "Gano X");
                estado = false;
            }else if(arreglo[matrizGanadora[i][0]-1].getText().equals("O") && arreglo[matrizGanadora[i][1]-1].getText().equals("O") && arreglo[matrizGanadora[i][2]-1].getText().equals("O")){
                arreglo[matrizGanadora[i][0]-1].setBackground(Color.green);
                arreglo[matrizGanadora[i][1]-1].setBackground(Color.green);
                arreglo[matrizGanadora[i][2]-1].setBackground(Color.green);
                JOptionPane.showMessageDialog(null, "Gano O");
                estado = false;
            }
        }
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(diseño.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(diseño.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(diseño.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(diseño.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new diseño().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnLimpiar;
    private javax.swing.JButton btnSalir;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel lblabel1;
    private javax.swing.JLabel lblabel3;
    private javax.swing.JLabel lblable2;
    private javax.swing.JLabel lblable4;
    private javax.swing.JLabel lblable5;
    private javax.swing.JLabel lblable6;
    private javax.swing.JLabel lblable7;
    private javax.swing.JLabel lblable8;
    private javax.swing.JLabel lblable9;
    // End of variables declaration//GEN-END:variables
}
